name: just-basics
on:
    push:
        branches:
            main
    workflow_dispatch:
        inputs:
            numbers:            
             description: 'just a number'
             type: number
             default: 18


jobs:
    newjob:
        runs-on: ubuntu-latest


        steps:
            - name: new-action
              run: echo "this is just basics"

