name: hellloworld

on:
  push:
    branches: [main]
  workflow_dispatch: 
    

jobs:
  build-hwp:
    runs-on: ubuntu-latest

    steps:
      - name: simple helloworld
        run: $echo "helloworld" 
      
