name: hellloworld

on:
  push:
    branches: [main]
  workflow_dispatch: 
    

jobs:
  build-hellow:
    runs-on: ubuntu-latest

    steps:
      - name: simple helloworld
        run: $echo ( "helloworld" )
      
