name: manualworkflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        type: string
        required: true
        default: hello


jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
    - name: 'simple name'
      run:  echo"${{ inputs.name }}" 
      
  
