name: manualworkflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        type: string
        required: true
        default: hello

      choices:
        description: 'choice'
        type: choice
        default: male
        options:
          - male
          - female


jobs:
  manual:
    runs-on: ubuntu-latest

    steps:
    - name: 'simple name'
      run:  echo "${{ inputs.name }}" 
    - name: 'choice'
      run: echo "${{ inputs.choices }}"
      
  
